% NOTE. The figues won't be closed automically. To change this behavior,
% set 'close_fig' to 'yes'.
% All figures will be saved in a folder named Figure in the same directory
% to the stats file. The directory can be specified with 'figdir'.
% 
% All coordinates are image index (starting from 1).
% If you are reading the coordinates from fslview, please note that the
% index starts from 0 in fslview.
% 

% those two files can be found in ./Data/
stats_file = '~/Downloads/PairedT_tfce_corrp_tstat2.nii.gz';
tval_file = '~/Downloads/PairedT_tstat2.nii.gz';


% Plot all slices with a p > 0.995, use skull-stripped MNI brain as background
% This will generate a lot of figures
MNIOverlay( stats_file, [],...
    'threshold', [0.995, 1],...
    'brain_threshold', [3000, 8000]); 

% I want to make figures bigger, 0 < img_sz < 1, default 0.15
MNIOverlay( stats_file, [],...
    'threshold', [0.995, 1],...
    'brain_threshold', [3000, 8000],...
    'img_sz', 0.8); 

% I just want to plot one sagittal slice
MNIOverlay( stats_file, [48 0 0],... 
    'threshold', [0.995, 1],...
    'brain_threshold', [3000, 8000]);

MNIOverlay( stats_file, [48 0 0],...
    'threshold', [0.995, 1]);

% same to
MNIOverlay( stats_file, [48],...
    'coord_style', 'x',...
    'threshold', [0.995, 1],...
    'brain_threshold', [3000, 8000]);

% I want to plot multiple sagittal slices
MNIOverlay( stats_file, [48:2:58],...
    'coord_style', 'x',...
    'threshold', [0.995, 1],...
    'brain_threshold', [3000, 8000]);

% I want to plot the results on a higher resolution MNI brain
MNIOverlay( stats_file, [48:2:58],...
    'coord_style', 'x',...
    'threshold', [0.995, 1],...
    'brain_threshold', [3000, 8000],...
    'brainfile', 'MNI152_T1_1mm_brain.nii.gz');


% I just want to plot a sagittal brain slice without any stats image
% The brain file must be given in full path if FSL is not installed
MNIOverlay( '', [48 0 0],...
    'brainfile', 'MNI152_T1_1mm_brain',...
    'brain_threshold', [3000, 8000]); 


% My stats image has both positive and negative values
% plot t stats image with both positive and negative values  
MNIOverlay( tval_file, [0 55 0],...
    'cm', cat( 3,  autumn(100), cool(100)),...
    'threshold', [4, 5; -2, -5],...
    'brain_threshold', [3000, 8000]);


% I want to plot several brain slices on one figure
figure;
SetPrintProp( gcf, 0.4, 0.4);
subplot( 221);
MNIOverlay( tval_file, [0 55 0],...
    'cm', cat( 3, autumn(100), cool(100)),...
    'threshold', [2, 5; -2  -5],...
    'hold', 'on',...
    'brain_threshold', [3000, 8000]);

subplot( 222);
MNIOverlay( tval_file, [60 0 0],...
    'cm', cat( 3, autumn(100), cool(100)),...
    'threshold', [2, 5; -2  -5],...
    'hold', 'on',...
    'brain_threshold', [3000, 8000]);

subplot( 223);
MNIOverlay( tval_file, [0 0 50],...
    'cm', cat( 3, autumn(100), cool(100)),...
    'threshold', [2, 5; -2  -5],...
    'hold', 'on',...
    'brain_threshold', [3000, 8000]);
  
% I want to add a marker at coordinate (x, y, z)
MNIOverlay( stats_file, [48 60 62],...
    'coord_style', 'xyz',...
    'show_marker', 'yes',...
    'marker_type', 'dot',... % 'dot' | 'cross' | 'dot+cross'
    'marker_size', 6,...
    'brain_threshold', [3000, 8000]); 

% I want to add a marker at coordinate (x, y, z)
MNIOverlay( stats_file, [48 60 62],...
    'coord_style', 'xyz',...
    'show_marker', 'yes',...
    'marker_type', 'dot',...
    'marker_size', 6,...
    'brainfile', 'MNI152_T1_1mm_brain',...
    'brain_threshold', [3000, 8000]);


% I am plotting only sagittal, axial or cronal slices, but I still want to add a marker
MNIOverlay( stats_file, [48 60 62],...
    'coord_style', 'x',...
    'cross', [48 60 62],...
    'cross_type', 'dot+cross',...
    'brain_threshold', [3000, 8000]); % 'dot' | 'cross' | 'dot+cross'

MNIOverlay( stats_file, [48 60 62],...
    'coord_style', 'x',...
    'cross', [48 60 62],...
    'cross_type', 'dot+cross',...
    'brain_threshold', [3000, 8000],...
    'brainfile', 'MNI152_T1_1mm_brain.nii.gz'); % 'dot' | 'cross' | 'dot+cross'


% I want to plot one brain slice along with a zoomed-in version
figure;
SetPrintProp( gcf, 0.25, 0.45);
subplot( 221);
MNIOverlay( stats_file, [48 0 0],...
    'coord_style', 'x',...
    'brain_threshold', [3000, 8000],...
    'rect', [0 0; 25 45; 40 65],...
    'hold', 'on');

subplot( 222);
MNIOverlay( stats_file, [48 0 0],...
    'coord_style', 'x',...
    'brain_threshold', [3000, 8000],...
    'rect', [0 0; 25 45; 40 65],...
    'rect_trim', 'yes',...
    'hold', 'on');

subplot( 223);
MNIOverlay( stats_file, [48 0 0],...
    'coord_style', 'x',...
    'brain_threshold', [3000, 8000],...
    'rect', [0 0; 25 45; 40 65],...
    'hold', 'on',...
    'brainfile', 'MNI152_T1_1mm.nii.gz');

subplot( 224);
MNIOverlay( stats_file, [48 0 0],...
    'coord_style', 'x',...
    'brain_threshold', [3000, 8000],...
    'rect', [0 0; 25 45; 40 65],...
    'rect_trim', 'yes',...
    'hold', 'on',...
    'brainfile', 'MNI152_T1_1mm.nii.gz');


% I want to outline significant clusters
figure;
SetPrintProp( gcf, 0.75, 0.45);
subplot( 141);
MNIOverlay( stats_file, [48 0 0],...
    'outline_overlay', 'yes',...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on');

% I want to outline significant clusters
subplot( 142);
MNIOverlay( stats_file, [48 0 0],...
    'outline_overlay', 'yes',...
    'outline_only', 'yes',...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on');

% I want to change the weight of that line
subplot( 143);
MNIOverlay( stats_file, [48 0 0],...
    'outline_overlay', 'yes',...
    'outline_only', 'yes',...
    'outline_linewidth', 2,...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on');

% I also want to change the outline color
subplot( 144);
MNIOverlay( stats_file, [48 0 0],...
    'outline_overlay', 'yes',...
    'outline_only', 'yes',...
    'outline_linewidth', 2,...
    'outline_color', 'b',...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on');


% I want to outline the ROI from standard atlas, e.g.,
% HarvardOxford-cort-maxprob-thr25-1mm.nii.gz
MNIOverlay( '', [0 0 80], 'brainfile', '/usr/local/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz',...
    'atlas', '/usr/local/fsl/data/atlases/HarvardOxford/HarvardOxford-cort-maxprob-thr25-1mm.nii.gz',...
    'atlas_value', [2],...
    'atlas_color', [0 0 1],...
    'atlas_linewidth', 2,...
    'atlas_hemi', 'r',... % 'l' | 'r' | 'lr' (default)
    'img_sz', 0.5, ...
    'brain_threshold', [3000 8000]);

% or we can do something like this
figure;
SetPrintProp( gcf, 0.6, 0.3);
subplot( 121);
% MNIOverlay( stats_file, [48 0 0], 'coord_style', 'x', 'brain_threshold', [3000, 8000], 'rect', [0 0; 25 45; 40 65], 'hold', 'on');
MNIOverlay( '', [0 0 80], 'brainfile', '/usr/local/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz',...
    'atlas', '/usr/local/fsl/data/atlases/HarvardOxford/HarvardOxford-cort-maxprob-thr25-1mm.nii.gz',...
    'atlas_value', [2],...
    'atlas_color', [0 0 1],...
    'atlas_linewidth', 2,...
    'atlas_hemi', 'r',... % 'l' | 'r' | 'lr' (default)
    'brain_threshold', [3000 8000],...
    'hold', 'on',...
    'rect', [40 70; 95 162; 0 0]);

subplot( 122);
MNIOverlay( '', [0 0 80], 'brainfile', '/usr/local/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz',...
    'atlas', '/usr/local/fsl/data/atlases/HarvardOxford/HarvardOxford-cort-maxprob-thr25-1mm.nii.gz',...
    'atlas_value', [2],...
    'atlas_color', [0 0 1],...
    'atlas_linewidth', 2,...
    'atlas_hemi', 'r',... % 'l' | 'r' | 'lr' (default)
    'brain_threshold', [3000 8000],...
    'hold', 'on',...
    'rect', [40 70; 95 162; 0 0],...
    'rect_trim', 'yes');


% plot vertical or horizontal lines to indicate where the plotted slices come from
c = flipud(hot);
figure;
SetPrintProp( gcf, 0.5, 0.6);
subplot(2, 4, 1);
MNIOverlay( stats_file, [48 0 0],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c,...
    'refline', [48:2:60],...
    'refline_view', 'z',...
    'img_sz', 0.7,...
    'refline_style', '-',...
    'refline_width', 1,...
    'refline_color', 'k');

subplot( 2, 4, 2);
MNIOverlay( stats_file, [0 0 48],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c);

subplot( 2, 4, 3);
MNIOverlay( stats_file, [0 0 50],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c);

subplot( 2, 4, 4);
MNIOverlay( stats_file, [0 0 52],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c);

subplot( 2, 4, 5);
MNIOverlay( stats_file, [0 0 54],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c);

subplot( 2, 4, 6);
MNIOverlay( stats_file, [0 0 56],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c);

subplot( 2, 4, 7);
MNIOverlay( stats_file, [0 0 58],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c);

subplot( 2, 4, 8);
MNIOverlay( stats_file, [0 0 60],...
    'threshold', [0.95, 1],...
    'brain_threshold', [3000, 8000],...
    'hold', 'on',...
    'cm', c);


