%% Subregion unique and common connections
threshold = 0.999;

fcdir = '~/Documents/RestfMRI/SourceData/Figure_4_sourcedata';
stats = { 'pos_OneSampT_tfce_corrp_tstat1.nii.gz'};
stats_abbrev = {'pos'};
roinames = { 'Aon', 'PirF', 'PirT', 'Tub'};
roi_abbrev = { 'Aon', 'PirF', 'PirT', 'Tub'};

savedir = fullfile( fcdir, 'Stats');
if ~exist( savedir, 'dir')
    mkdir( savedir);
end

nbrois = length( roinames);
vol = cell( nbrois, length( stats));
for k = 1 : nbrois
    for stats_ind = 1 : length( stats)
        vol{ k, stats_ind} = MRIread( fullfile( fcdir, roinames{ k}, stats{ stats_ind}));
        vol{ k, stats_ind}.vol = double( vol{ k, stats_ind}.vol > threshold);
    end
end

stats_mask = cell( 1, length( stats));
for stats_ind = 1 : length( stats)
    tmp = cellfun( @(x) x.vol, vol(:, stats_ind), 'UniformOutput', false);
    tmp = cat( 4, tmp{:}) > 0;
    stats_mask{ 1, stats_ind} = sum( tmp, 4);
end

for k = 1 : nbrois
    C = nchoosek( 1:nbrois, k);    
    for x = 1 : size( C, 1)
        for stats_ind = 1 : length( stats)
            overlap = vol( C(x, :), stats_ind);
            overlap = cellfun( @(x) x.vol, overlap, 'UniformOutput', false);
            overlap = cat( 4, overlap{:});
            overlap = double( sum( overlap, 4) > 0);
            
            overlap = overlap .* ( stats_mask{ 1, stats_ind} == k);
            
            if any( overlap(:))
                tmp_name = [];
                for tmp_idx = 1 : k
                    if tmp_idx == 1
                        tmp_name = roi_abbrev{ C( x, tmp_idx)};
                    else
                        tmp_name = [tmp_name, '_', roi_abbrev{ C( x, tmp_idx)}];
                    end
                end

                % nb of clusters, 
                name = [stats_abbrev{stats_ind}, '_Clust_', num2str( k), '_', tmp_name];
                fprintf( '%s\n', name);

                tmp = vol{ 1};
                tmp.vol = overlap;
                MRIwrite( tmp, fullfile( savedir, [name, '.nii.gz']), 'float');
            end 
            
        end 
    end
end

% t value maps of unique connections
tstat = 'pos_OneSampT_tstat1.nii.gz';
mask_prefix = 'pos_Clust_1_';
prefix = 'pos_Clust_1_tstat_';
for k = 1 : nbrois
    tmap = MRIread( fullfile( fcdir, roinames{ k}, tstat));
    
    maskfile = fullfile( savedir, [mask_prefix, roinames{ k}]);
    mask = MRIread( maskfile);
    
    tmap.vol = tmap.vol .* mask.vol;
    MRIwrite( tmap, fullfile( savedir, [prefix, roinames{k}, '.nii.gz']), 'float');
end





%% colormap
figdir = '~/Documents/RestfMRI/Figures/SubregionFC_Tstats';

N = 201;
S = 1000;
lo_S = 255;
% lo_S = 400;

lo = [204, 51, 255]/S;
hi = [204, 51, 255]/255;
map = [linspace( lo(1), hi(1), N)',...
    linspace( lo(2), hi(2), N)',...
    linspace( lo(3), hi(3), N)'];
purple_map = flipud( map);

lo = [0, 255, 0]/S;
hi = [0, 255, 0]/lo_S;
map = [linspace( lo(1), hi(1), N)',...
    linspace( lo(2), hi(2), N)',...
    linspace( lo(3), hi(3), N)'];
green_map = flipud( map);


lo = [255, 0, 0]/S;
hi = [255, 0, 0]/lo_S;
map = [linspace( lo(1), hi(1), N)',...
    linspace( lo(2), hi(2), N)',...
    linspace( lo(3), hi(3), N)'];
red_map = flipud( map);

lo = [0, 0, 255]/S;
hi = [0, 0, 255]/lo_S;
map = [linspace( lo(1), hi(1), N)',...
    linspace( lo(2), hi(2), N)',...
    linspace( lo(3), hi(3), N)'];
blue_map = flipud( map);


% plot colormap
figure;
SetPrintProp( gcf, 0.02, 0.2);
subplot( 221);
imagesc( permute( red_map, [1 3 2]));
set( gca, 'XTick', [],...
    'YTick', 1:50:201,...
    'YDir', 'normal',...
    'fontsize', 6,...
    'TickLength', [1, 1] * 0.03);

subplot( 222);
imagesc( permute( green_map, [1 3 2]));
set( gca, 'XTick', [],...
    'YTick', 1:50:201,...
    'YDir', 'normal',...
    'fontsize', 6,...
    'TickLength', [1, 1] * 0.03);

subplot( 223);
imagesc( permute( purple_map, [1 3 2]));
set( gca, 'XTick', [],...
    'YTick', 1:50:201,...
    'YDir', 'normal',...
    'fontsize', 6,...
    'TickLength', [1, 1] * 0.03);

subplot( 224);
imagesc( permute( blue_map, [1 3 2]));
set( gca, 'XTick', [],...
    'YTick', 1:50:201,...
    'YDir', 'normal',...
    'fontsize', 6,...
    'TickLength', [1, 1] * 0.03);

if ~exist( figdir, 'dir')
    mkdir( figdir);
end

print( gcf, '-dpdf', '-fillpage', fullfile( figdir, 'colormap.pdf'));



%% Functional connectivity subregion specific on surface
surf_figdir = fullfile( figdir, 'Surf');
if ~exist( surf_figdir, 'dir')
    mkdir( surf_figdir);
end

thresholds = {[3.2, 15.9],...
    [3.2, 14.7],...
    [3.1, 7.8],...
    [3.2, 11.3]};
cmaps = {red_map, purple_map, blue_map, green_map};
roinames = {'Aon', 'Tub', 'PirF', 'PirT'};

for roi_idx = 1 : 4    
    roiname = roinames{ roi_idx};

    cd( fullfile( '~/Documents/RestfMRI/SourceData/Figure_4_sourcedata', roiname, 'Resol1mm'));

    % brain surface
    rh_curv = read_curv( '~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/rh.curv');
    lh_curv = read_curv( '~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/lh.curv');
    [lh_vertex, lh_faces] = read_surf('~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/lh.inflated');
    lh_faces = lh_faces + 1;
    [rh_vertex, rh_faces] = read_surf('~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/rh.inflated');
    rh_faces = rh_faces + 1;

    % combine left and right
    vertex = cat( 1, lh_vertex, rh_vertex);
    faces = cat( 1, lh_faces, rh_faces + size( lh_vertex, 1));
    curv = cat( 1, lh_curv, rh_curv);
    
    g = MRIread( ['rh.pos_OneSampT_tstat1_1mm_threshold_1mm.mgh']);
    rh_label = g.vol(:);

    g = MRIread( ['lh.pos_OneSampT_tstat1_1mm_threshold_1mm.mgh']);
    lh_label = g.vol(:);

    label = {cat( 1, lh_label, rh_label)};

    % All weighted vertices, Nx2 ([index, value]) or Nx1 ([index]) label which
    % is specified by label_type
    label_type = {'surf'};
    % threshold, each cell is a Mx2 matrix
    threshold = thresholds( roi_idx);
    % colormap, each cell is a Hx3xM matrix
    cmap = cmaps( roi_idx);
    % cmap = {[204, 51, 255]/255};


    view_angels1 = {[-90, 0],...
        [180, -90],...
        [90, 0],...
        [0, 90]};
    view_angels2 = {[90, 0],...
        [180, -90],...
        [-90, 0],...
        [0, 90]};

    xlim = [-150, 150];
    ylim = [-127, 127];
    zlim = [-85 85];
    for k = 1 : 4
        figure;
        SetPrintProp( gcf, 0.35, 0.3);
        subplot( 121);
        SurfacePlot( gca, lh_vertex, lh_faces,...
            'label', {lh_label},...
            'label_type', label_type,...
            'threshold', threshold,...
            'cmap', cmap,...
            'curv', lh_curv,...
            'view_angle', view_angels1{k},...
            'is_discrete', 'yes');    
        axis equal
        set( gca,...
            'zLim', zlim,...
            'xlim', xlim,...
            'ylim', ylim,...
            'color', 'none');

        subplot( 122);
        SurfacePlot( gca, rh_vertex, rh_faces,...
            'label', {rh_label},...
            'label_type', label_type,...
            'threshold', threshold,...
            'cmap', cmap,...
            'curv', rh_curv,...
            'view_angle', view_angels2{k},...
            'is_discrete', 'yes');    
        axis equal
        set( gca,...
            'zLim', zlim,...
            'xlim', xlim,...
            'ylim', ylim,...
            'color', 'none');

%         print( gcf, '-dpdf', '-fillpage', fullfile( surf_figdir, [roiname, '_', num2str(k), '_2.pdf']));
    end
    
end % roi





%% subregion-specific coronal, axial, and sagittal view
stdbrain = '/usr/local/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz';

%
img2plot = '~/Documents/RestfMRI/SourceData/Figure_4_sourcedata/Aon/Resol1mm/pos_OneSampT_tstat1_1mm_threshold.nii.gz';
prefix = 'UAon';
threshold = [3.2, 15.9];

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [93]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'x',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', red_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_sagittal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [85 123]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'y',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', red_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_cronal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [47 51 67]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'z',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', red_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_axial.pdf']));


%
img2plot = '~/Documents/RestfMRI/SourceData/Figure_4_sourcedata/Tub/Resol1mm/pos_OneSampT_tstat1_1mm_threshold.nii.gz';
prefix = 'UTub';
threshold = [3.2, 14.7];


figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [89 103]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'x',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', purple_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_sagittal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [191]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'y',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', purple_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_cronal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [51]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'z',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', purple_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_axial.pdf']));


%
img2plot = '~/Documents/RestfMRI/SourceData/Figure_4_sourcedata/PirF/Resol1mm/pos_OneSampT_tstat1_1mm_threshold.nii.gz';
prefix = 'UPirF';
threshold = [3.1, 7.8];


figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [89]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'x',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', blue_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_sagittal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [111 131]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'y',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', blue_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_cronal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [107]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'z',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', blue_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_axial.pdf']));




img2plot = '~/Documents/RestfMRI/SourceData/Figure_4_sourcedata/PirT/Resol1mm/pos_OneSampT_tstat1_1mm_threshold.nii.gz';
prefix = 'UPirT';
threshold = [3.2, 11.3];

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [95 139]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'x',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', green_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_sagittal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [111 137 151]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'y',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', green_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_cronal.pdf']));

figure;
SetPrintProp( gcf, 0.3, 0.3);
cnt = 1;
for s = [73 85]
    subplot( 2, 2, cnt);
    cnt = cnt + 1;
    MNIOverlay( img2plot, s,...
        'coord_style', 'z',...
        'brain_threshold', [3, 8]*1000,...
        'threshold', threshold,...
        'cm', green_map,...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end
print( gcf, '-dpdf', '-fillpage', fullfile( figdir, [prefix, '_axial.pdf']));



%% function connectivity common to all on surface
cd( '~/Documents/RestfMRI/SourceData/Figure_5_sourcedata/');
% brain surface
rh_curv = read_curv( '~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/rh.curv');
lh_curv = read_curv( '~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/lh.curv');
[lh_vertex, lh_faces] = read_surf('~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/lh.inflated');
lh_faces = lh_faces + 1;
[rh_vertex, rh_faces] = read_surf('~/Desktop/test/PiriformLabel/cvs_avg35_inMNI152/surf/rh.inflated');
rh_faces = rh_faces + 1;

g = MRIread( 'rh.Figure_5_pos_Common2AllROIs_1mm.mgh');
rh_label = g.vol(:);

g = MRIread( 'lh.Figure_5_pos_Common2AllROIs_1mm.mgh');
lh_label = g.vol(:);

% All weighted vertices, Nx2 ([index, value]) or Nx1 ([index]) label which
% is specified by label_type
label_type = {'surf'};
% threshold, each cell is a Mx2 matrix
threshold = {[3 5]};
% colormap, each cell is a Hx3xM matrix
cmap = {[1 0 0]};

figdir = '~/Documents/RestfMRI/Figures/FuncCommon2All';
if ~exist( figdir, 'dir')
    mkdir( figdir);
end

view_angels1 = {[-90, 0],...
    [180, -90],...
    [90, 0],...
    [0, 90]};
view_angels2 = {[90, 0],...
    [180, -90],...
    [-90, 0],...
    [0, 90]};
xlim = [-150, 150];
ylim = [-127, 127];
zlim = [-85 85];
for k = 1 : 4
    figure;
    SetPrintProp( gcf, 0.35, 0.3);
    subplot( 121);
    SurfacePlot( gca,...
        lh_vertex,...
        lh_faces,...
        'label', {lh_label},...
        'label_type', label_type,...
        'threshold', threshold,...
        'cmap', cmap,...
        'curv', lh_curv,...
        'view_angle', view_angels1{k},...
        'is_discrete', 'yes');
    axis equal
    set( gca,...
        'zLim', zlim,...
        'xlim', xlim,...
        'ylim', ylim,...
        'color', 'none');
    
    subplot( 122);
    SurfacePlot( gca, rh_vertex, rh_faces,...
        'label', {rh_label},...
        'label_type', label_type,...
        'threshold', threshold,...
        'cmap', cmap,...
        'curv', rh_curv,...
        'view_angle', view_angels2{k},...
        'is_discrete', 'yes');
    axis equal
    set( gca,...
        'zLim', zlim,...
        'xlim', xlim,...
        'ylim', ylim,...
        'color', 'none');
    
    print( gcf, '-dpdf', '-fillpage', fullfile( figdir, ['common2All_', num2str(k), '.pdf']));
end


roi = '~/Documents/RestfMRI/SourceData/Figure_5_sourcedata/Figure_5_pos_Common2AllROIs_1mm.nii.gz';
stdbrain = '/usr/local/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz';

figure;
SetPrintProp( gcf, 0.3, 0.3);
subplot( 2, 4, 1);
MNIOverlay( roi, [69],...
    'coord_style', 'x',...
    'brain_threshold', [3, 8]*1000,...
    'cm', [1 0 0],...
    'hold', 'on',...
    'brainfile', stdbrain,...
    'fontsize', 6); 
subplot( 2, 4, 2);
MNIOverlay( roi, [113],...
    'coord_style', 'x',...
    'brain_threshold', [3, 8]*1000,...
    'cm', [1 0 0],...
    'hold', 'on',...
    'brainfile', stdbrain,...
    'fontsize', 6);%,...
%     'refline', [125:3:141], 'refline_view', 'y', 'refline_style', '-', 'refline_width', 1,'refline_color', 'k', 'brainfile', stdbrain);

subplot( 2, 4, 3);
MNIOverlay( roi, [91],...
    'coord_style', 'x',...
    'brain_threshold', [3, 8]*1000,...
    'cm', [1 0 0],...
    'hold', 'on',...
    'brainfile', stdbrain,...
    'fontsize', 6);%,...
%     'refline', [125:3:141], 'refline_view', 'y', 'refline_style', '-', 'refline_width', 1,'refline_color', 'k', 'brainfile', stdbrain);

cnt = 5;
for s = [54 62 70]
    subplot( 2, 4, cnt);
    cnt = cnt + 1;
    MNIOverlay( roi, s,...
        'coord_style', 'z',...
        'brain_threshold', [3, 8]*1000,...
        'cm', [1 0 0],...
        'hold', 'on',...
        'brainfile', stdbrain,...
        'fontsize', 6);
end

print( gcf, '-dpdf', '-fillpage', '~/Documents/RestfMRI/Figures/FuncCommon2All/slice_view.pdf');

